kind: Deployment
apiVersion: apps/v1
metadata:
  name: faraway-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faraway-front
  template:
    metadata:
      labels:
        app: faraway-front
    spec:
      containers:
      - name: faraway-front
        image: egych/faraway-front
        ports:
        - containerPort: 80
